= spell

image:https://github.com/simonnagl/spell/workflows/Go/badge.svg[Go,link=https://github.com/simonnagl/spell/actions?query=branch:master]
image:https://coveralls.io/repos/github/simonnagl/spell/badge.svg?branch=master&t=47TqXT[Coverage Status,link=https://coveralls.io/github/simonnagl/spell?branch=master]

spell word(s) using a spelling alphabet.

== Installation

=== Golang

	go install github.com/simonnagl/spell/cmd/spell

=== Docker

    docker run --rm simonnagl/spell

=== Binary

Download from https://github.com/simonnagl/spell/releases[GitHub Releases].

== Synopsis

	spell [-hlv] <word(s)>

== Options

*-h* :: Print this usage note (Default: false)
*-l* alphabet:: Spelling alphabet to use (Default: en)
*-v* :: Print version info (Default: false)

== Spelling alphabets

[cols="h,3*"]
|===

| cs | Czech | čeština |
| da | Danish | dansk |
| de-AT | Austrian German | Österreichisches Deutsch | ÖNORM A 1081
| de-CH | Swiss High German | Schweizer Hochdeutsch |
| de-DE | German (Germany) | Deutsch | DIN 5009
| en | English | English | ICAO, NATO
| en-GB | British English | British English |
| es | Spanish | español |
| fi | Finnish | suomi |
| fr | French | français |
| it | Italian | italiano |
| nl | Dutch | Nederlands |
| no | Norwegian Bokmål | norsk bokmål |
| pt-BR | Brazilian Portuguese | português |
| pt-PT | European Portuguese | português europeu |
| ro | Romanian | română |
| sl | Slovenian | slovenščina |
| sv | Swedish | svenska |
| tr | Turkish | Türkçe |

|===

== Examples

To set a default language you may use an alias:

	alias spell="spell -l de"

== Copyright

Copyright (C) 2020 Simon Nagl. +
Free use of this software is granted under the terms of the MIT License.
