package main

import (
	"bytes"
	"flag"
	"fmt"
	"github.com/simonnagl/spell/test"
	"io/ioutil"
	"os"
	"testing"
)

func TestManpage(t *testing.T) {
	commitedManpage := readCommitedManpage(t)
	generatedManpage := generateManpage()

	if commitedManpage != generatedManpage {
		writeGeneratedManpage(t, generatedManpage)

		t.Error("The manpage generated by this test does not match the commited manpage of this project.",
			"The manpage is generated to reduce duplicate information.",
			"The manpage is also commited because we include parts of it into the README.",
			"Fix the generated manpage or adopt the commited manpage to fix this test.")
	}
}

func readCommitedManpage(t *testing.T) string {
	const commitedManpageName = "../../man-page.adoc"

	commitedManpage, err := ioutil.ReadFile(commitedManpageName)
	if err != nil {
		t.Fatal("Could not read file", commitedManpageName, err)
	}
	return string(commitedManpage)
}

func generateManpage() string {
	cleanup := test.ClearCommandLine()
	defer cleanup()
	DefineFlags()

	return fmt.Sprintf(`= spell(1)
Simon Nagl
v0.1.0
:doctype: manpage

== Name

spell - spell word(s) using a spelling alphabet.

== Synopsis

%s

== Options

%s
== Spelling alphabets

%s
== Examples

To set a default language you may use an alias:

	alias spell="spell -l de"

== Copyright

Copyright (C) 2020 Simon Nagl. +
Free use of this software is granted under the terms of the MIT License.
`,
		synopsis(),
		options(),
		alphabetsManpage())
}

func options() string {
	buf := bytes.Buffer{}
	flag.VisitAll(func(f *flag.Flag) {
		fType, fUsage := flag.UnquoteUsage(f)
		buf.WriteString(fmt.Sprintf("*-%s* %s:: %s (Default: %s)\n", f.Name, fType, fUsage, f.DefValue))
	})
	return buf.String()
}

func writeGeneratedManpage(t *testing.T, generatedManpage string) {
	fName := "man-page.test.adoc"
	f, err := os.Create(fName)
	if err != nil {
		t.Fatal("Could not create file", f, err)
	}
	_, err = f.WriteString(generatedManpage)
	if err != nil {
		t.Fatal("Could not write to file", f, err)
	}
}

func TestReadme(t *testing.T) {
	const commitedReadmeName = "../../README.adoc"

	commitedReadme, err := ioutil.ReadFile(commitedReadmeName)
	if err != nil {
		t.Fatal("Could not read file", commitedReadmeName, err)
	}

	cleanup := test.ClearCommandLine()
	defer cleanup()
	DefineFlags()

	generatedManpage := fmt.Sprintf(`= spell

image:https://github.com/simonnagl/spell/workflows/Go/badge.svg[Go,link=https://github.com/simonnagl/spell/actions?query=branch:master]
image:https://coveralls.io/repos/github/simonnagl/spell/badge.svg?branch=master&t=47TqXT[Coverage Status,link=https://coveralls.io/github/simonnagl/spell?branch=master]

spell word(s) using a spelling alphabet.

== Synopsis

	%s

== Options

%s
== Spelling alphabets

[cols="h,2*"]
|===

%s
|===

== Examples

To set a default language you may use an alias:

	alias spell="spell -l de"

== Copyright

Copyright (C) 2020 Simon Nagl. +
Free use of this software is granted under the terms of the MIT License.
`,
		synopsis(),
		options(),
		alphabetsReadme())

	if string(commitedReadme) != generatedManpage {
		fName := "readme.test.adoc"
		f, err := os.Create(fName)
		if err != nil {
			t.Fatal("Could not create file", f, err)
		}
		_, err = f.WriteString(generatedManpage)
		if err != nil {
			t.Fatal("Could not write to file", f, err)
		}
		t.Error("The README generated by this test does not match the commited REAMDME of this project.",
			"The README is generated to reduce duplicate information.",
			"The README is also commited because we want to make it readable.",
			"Fix the generated README or adopt the commited README to fix this test.")
	}
}

func alphabetsManpage() string {
	return formatAllAplphabet(func(a alphabetView) string {
		return fmt.Sprintf("*%s* :: %s -- %s\n", a.tag, a.englishName, a.selfName)
	})
}

func formatAllAplphabet(format func(a alphabetView) string) string {
	allAlphabet := alphabetViewModel()
	buf := bytes.Buffer{}

	for _, a := range allAlphabet {
		buf.WriteString(format(a))
	}

	return buf.String()
}

func alphabetsReadme() string {
	return formatAllAplphabet(func(a alphabetView) string {
		return fmt.Sprintln("|", a.tag, "|", a.englishName, "|", a.selfName)
	})
}
