name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.11', '1.12', '1.13', '1.14']

    steps:

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out repository
      uses: actions/checkout@v2

    - name: Test
      run: go test -coverprofile=profile.cov ./...

    - name: Upload coverage to Coveralls
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: profile.cov

    - name: Build
      run: go build -v github.com/simonnagl/spell/cmd/spell
